stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: build
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: NodeTool@0
            displayName: Use Node 22.x
            inputs:
              versionSpec: 22.x

          - script: |
              corepack enable
              corepack prepare pnpm@9.12 --activate
            displayName: "Setup pnpm"

          - script: pnpm install
            displayName: pnpm install --frozen-lockfile

          - script: pnpm audit --registry=https://registry.npmjs.org --audit-level=high --production
            displayName: pnpm audit

          - script: pnpm build
            displayName: pnpm build

          - script: pnpm lint
            displayName: pnpm lint
