stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: test
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: NodeTool@0
            displayName: Use Node 22.x
            inputs:
              versionSpec: 22.x

          - script: |
              corepack enable
              corepack prepare pnpm@9.12 --activate
            displayName: "Setup pnpm"

          - bash: |
              echo "##vso[task.setvariable variable=imjs_test_super_user_password;]$test_super_password"
            displayName: "Add config to environment"
            env:
              test_super_password: $(imjs_super_user_password)

          - script: pnpm install
            displayName: pnpm install --frozen-lockfile

          - script: pnpm build
            displayName: pnpm build

          - script: pnpm test
            displayName: pnpm test
