stages:
  - stage: Publish
    displayName: Publish

    variables:
      - group: "Caleb - iTwin GitHub Token"
      - group: "Caleb - npmjs publish token"
      - name: REPO_URL
        value: github.com/iTwin/itwins-client/

    jobs:
      - job: build
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: NodeTool@0
            displayName: Use Node 22.x
            inputs:
              versionSpec: 22.x

          - script: |
              corepack enable
              corepack prepare pnpm@9.12 --activate
            displayName: "Setup pnpm"

          - task: npmAuthenticate@0
            inputs:
              workingFile: .npmrc

          - script: pnpm install
            displayName: pnpm install --frozen-lockfile

          - script: pnpm build
            displayName: pnpm build

          - script: |
              git config --global user.email imodeljs-admin@users.noreply.github.com
              git config --global user.name imodeljs-admin
              git remote set-url origin "https://$(GITHUBTOKEN)@$(REPO_URL)"
              pnpm publish-package --branch main --message "Version bump [skip ci]" --token $NPM_AUTH_TOKEN
            displayName: "Publish packages"
            env:
              NPM_AUTH_TOKEN: $(npmToken)
